#!/bin/bash
# 任务管理系统测试脚本

echo "🧪 任务管理系统测试指南"
echo "================================"
echo ""
echo "任务管理系统已经集成到 Oxide CLI 中，你可以通过与 AI 对话来使用它。"
echo ""
echo "## 启动 Oxide CLI"
echo ""
echo "cargo run --release"
echo ""
echo "## 测试场景"
echo ""
echo "### 1️⃣ 创建任务"
echo ""
echo "你: 请创建一个任务，标题是'实现用户认证'，描述是'实现 JWT 认证系统，包括登录、注册和令牌刷新'"
echo ""
echo "AI 会调用 TaskCreate 工具创建任务，并返回任务 ID。"
echo ""
echo "### 2️⃣ 列出所有任务"
echo ""
echo "你: 列出所有任务"
echo ""
echo "AI 会调用 TaskList 工具显示所有任务的摘要。"
echo ""
echo "### 3️⃣ 查看任务详情"
echo ""
echo "你: 查看任务 #1 的详情"
echo ""
echo "AI 会调用 TaskGet 工具显示完整的任务信息。"
echo ""
echo "### 4️⃣ 更新任务状态"
echo ""
echo "你: 将任务 #1 的状态更新为 in_progress"
echo ""
echo "AI 会调用 TaskUpdate 工具更新任务状态。"
echo ""
echo "### 5️⃣ 创建带依赖的任务"
echo ""
echo "你: 创建一个新任务'编写测试'，它依赖于任务 #1"
echo ""
echo "AI 会创建任务并设置依赖关系。"
echo ""
echo "### 6️⃣ 复杂场景：多任务管理"
echo ""
echo "你: 帮我规划一个功能开发，包括以下步骤："
echo "    1. 设计数据库模型"
echo "    2. 实现 API 接口"
echo "    3. 编写单元测试"
echo "    4. 集成测试"
echo "    请为每个步骤创建任务，并设置合理的依赖关系。"
echo ""
echo "AI 会创建多个任务并设置依赖关系。"
echo ""
echo "================================"
echo ""
echo "## 直接测试（不通过 AI）"
echo ""
echo "如果你想直接测试任务管理功能，可以运行单元测试："
echo ""
echo "cargo test -p oxide-tools task"
echo ""
echo "或者查看测试代码了解 API 用法："
echo ""
echo "cat crates/oxide-tools/src/task/tools/create.rs"
echo "cat crates/oxide-tools/src/task/tools/list.rs"
echo "cat crates/oxide-tools/src/task/tools/get.rs"
echo "cat crates/oxide-tools/src/task/tools/update.rs"
echo ""
